# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b6b4dbab0abcc68cd64fbddbec387bf54f7a7f5578d7e8683f3f0442d60e02d73081c0409afe12aec5290cc3fd218428b70e70a2e9a30d9ceac83fd729868ab

test:
  secret_key_base: 389003fb07301ecb5703497f94039dcd886f6b7fe479f3cc9c6ecbbf6b31352d89b68c3630b289526e9bfbbe376970681e617b424592766f3d32b13d14d274f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
